name: Ejecutar script LaPelotona

on:
  schedule:
    - cron: '0 11 * * *'   # 11:00 UTC (6:00 Perú)
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      CRED_TYPE: ${{ secrets.CRED_TYPE }}
      CRED_PROJECT_ID: ${{ secrets.CRED_PROJECT_ID }}
      CRED_PRIVATE_KEY_ID: ${{ secrets.CRED_PRIVATE_KEY_ID }}
      CRED_PRIVATE_KEY: ${{ secrets.CRED_PRIVATE_KEY }}
      CRED_CLIENT_EMAIL: ${{ secrets.CRED_CLIENT_EMAIL }}
      CRED_CLIENT_ID: ${{ secrets.CRED_CLIENT_ID }}
      CRED_AUTH_URI: ${{ secrets.CRED_AUTH_URI }}
      CRED_TOKEN_URI: ${{ secrets.CRED_TOKEN_URI }}
      CRED_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.CRED_AUTH_PROVIDER_X509_CERT_URL }}
      CRED_CLIENT_X509_CERT_URL: ${{ secrets.CRED_CLIENT_X509_CERT_URL }}
      CRED_UNIVERSE_DOMAIN: ${{ secrets.CRED_UNIVERSE_DOMAIN }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytz

      - name: Ejecutar script
        run: |
          python script.py

      - name: Configurar usuario git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add y commit pagina.html
        run: |
          git add pagina.html
          git commit -m "Actualizar pagina.html automáticamente" || echo "Sin cambios para commitear"

      - name: Pull antes de push
        run: |
          git pull --rebase origin main

      - name: Push pagina.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

      - name: Enviar pagina.html por correo
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "Archivo pagina.html actualizado"
          to: ${{ secrets.GMAIL_USER }}
          from: ${{ secrets.GMAIL_USER }}
          body: "Adjunto el archivo pagina.html generado automáticamente."
          attachments: pagina.html
